### ISSUE TITLE
Add a command to export to HTML

### ISSUE THREAD

**Issue by vrutkovs** [elmiko/okd-camgi#26]
Exporting to static HTML would allow us to merge this with https://github.com/openshift/must-gather or add a new CI step to produce the report as an artifact.

Most likely we'd have to rip out the logs and do some kind of lazy loading to keep the report small though

**Comment by elmiko** [comment]
the tool currently creates a single static html page, although it can get quite large depending on the must gather.

by default, running `okd-camgi some/must-gather` will produce the static file in a new temp directory, but if you use the `--output` flag you can specify the filename to dump the contents to.

is this what you are looking for, or would you like to see an option where it outputs the static html to stdout?

**Comment by elmiko** [comment]
fwiw, i do have a fork of must-gather that includes a commit to produce a camgi html file, see https://github.com/elmiko/must-gather/commit/d5f6683ed444b4c7bff0105c3d2a68cb29f25089

**Comment by elmiko** [comment]
@vrutkovs i'm curious if there is something to do here or not?

 it sounds like the tool creates what you are asking for, but i want to make sure before closing this out.

**Comment by vrutkovs** [comment]
Yeah, an option to include it in must-gather looks more appealing, closing
